local M = {}

local C = {
  primary_bold = '#105bd8',
  primary = '#0b3d91',
  fg = '#061f4a',
  fg_bold = '#212121',
  gray = '#5b616b',
  gray_dark = '#323a45',
  gray_light = '#aeb0b5',
  gray_lighter = '#d6d7d9',
  gray_lightest = '#f1f1f1',
  fg_soft = '#494440',
  bg = '#e4e2e0',
  bg2 = '#8ba6ca',
  fg_softer = '#8c8a8a',
  white = '#ffffff',
  alt_bolder = '#02bfe7',
  alt = '#046b99',
  alt_bold = '#00a6d2',
  alt_soft = '#9bdaf1',
  alt_bg = '#e1f3f8',
  red_bolder = '#dd361c',
  red = '#801a17',
  red_bold = '#c22c1f',
  red_soft = '#c4837a',
  red_bg = '#f9e0de',
  gold = '#61330e',
  gold_bold = '#965c12',
  gold_bolder = '#ff9d1e',
  gold_soft = '#f9aa43',
  gold_softer = '#ffc375',
  gold_bg = '#ffebd1',
  green = '#174A24',
  green_bold = '#29783b',
  green_soft = '#4aa564',
  green_softer = '#94bfa2',
  green_bg = '#e7f4e4',
  blue = '#205493',
  blue_bold = '#426b9e',
  blue_bg = '#dce4ef',
  purple_bold = '#6F46C8',
  purple = '#4c2c92',
}

M.default = {
  none = 'NONE',

  fg = {
    normal = C.fg,
    bold = C.fg_bold,
    soft = C.fg_soft,
    softer = C.fg_softer,
    softest = C.gray_light,
    primary_bold = C.primary_bold,
    primary = C.primary,
    alt = C.alt,
    alt_bold = C.alt_bold,
    alt_bolder = C.alt_bolder,
    alt_soft = C.alt_soft,
    blue = C.blue,
    blue_bold = C.blue_bold,
    red_bolder = C.red_bolder,
    red_bold = C.red_bold,
    red_soft = C.red_soft,
    red = C.red,
    gold_bolder = C.gold_bolder,
    gold_bold = C.gold_bold,
    gold = C.gold,
    gold_soft = C.gold_soft,
    gold_softer = C.gold_softer,
    green_soft = C.green_soft,
    green_softer = C.green_softer,
    green = C.green,
    green_bold = C.green_bold,
    purple_bold = C.purple_bold,
    purple = C.purple,
  },

  bg = {
    normal = C.bg,
    normal2 = C.bg2,
    popup = C.gray_lightest,
    popup_line = C.blue_bg,
    float = C.gray_lightest,
    alt = C.alt_bg,
    blue = C.blue_bg,
    red = C.red_bg,
    gold = C.gold_bg,
    green = C.green_bg,
    gray = C.gray,
    gray_dark = C.gray_dark,
    current_line = C.gray_lighter,
    visual = C.gold_softer,
    inc_search = C.gold_soft,
  },

  white = C.white,

  diff_add = C.green_bg,
  diff_delete = C.red_bg,
  diff_change = C.green_bg,
  diff_text = C.green_softer,
}

M.term = {
  black = C.bg,
  bright_black = C.gray,

  red = C.red,
  bright_red = C.red_bolder,

  green = C.green,
  bright_green = C.green_bold,

  yellow = C.gold,
  bright_yellow = C.gold_bold,

  blue = C.primary,
  bright_blue = C.primary_bold,

  purple = C.purple,
  bright_purple = C.purple_bold,

  cyan = C.blue,
  bright_cyan = C.blue_bold,

  white = C.fg,
  bright_white = C.fg_bold,
}

return M
