[colors.bright]
black =   '#494440'
red =     '#af1608'
green =   '#4c6129'
yellow =  '#705700'
blue =    '#0d50c5'
magenta = '#952197'
cyan =    '#006442'
white =   '#ffffff'

[colors.normal]
black =   '#080808'
red =     '#7a0047'
green =   '#174A24'
yellow =  '#644117'
blue =    '#002fa7'
magenta = '#5400a8'
cyan =    '#004347'
white =   '#9c958d'

[colors.primary]
background = '#e4e2e0'
foreground = '#061f4a'
